version: "3.9"

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: "http://localhost:3000"
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - todos
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    working_dir: /app
    command: sh -c "npm run db:migrate && node src/main.js"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=todos
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - todos
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - todos

networks:
  todos:
